<?php
/**
 * Reusable Template Functions
 *
 * Functions that can be used directly inside theme files to add functionality/
 * features to the theme.
 *
 * @package Album
 * @subpackage TemplateTags
 * @author Ben Gillbanks <ben@prothemedesign.com>
 * @license http://www.gnu.org/licenses/gpl-2.0.html GNU Public License
 */


/**
 * Display the post time in a human readable format.
 *
 * The time will display in the format '5 minutes ago' with the duration and
 * unit changing depending upon how long ago the content was published. Once the
 * content is older than 60 days it will display the publication date which is
 * formatted according to the date format set in the WordPress admin.
 *
 * @return string
 */
function album_human_time_diff() {

	$post_time = get_the_time( 'U' );
	$time_now = date( 'U' );

	/**
	 * Use human time if less that 60 days ago, otherwise display the date
	 * Uses the WordPress internal function human_time_diff
	 * 60 seconds * 60 minutes * 24 hours * 60 days.
	 */
	if ( $post_time > $time_now - ( 60 * 60 * 24 * 60 ) ) {

		$human_time = sprintf( esc_html__( '%s ago', 'album' ), human_time_diff( $post_time, current_time( 'timestamp' ) ) );

	} else {

		$human_time = get_the_date();

	}

	return sprintf( '<span class="post-human-time updated date published">%s</span>', $human_time );

}


/**
 * Get post thumbnail url.
 *
 * If a thumbnail doesn't exist then use the first attachment. This reduces user
 * confusion since they don't always understand or set a featured image.
 *
 * @param integer $post_id ID for the post that you want to get the thumbnail
 *                         url for.
 * @param string  $thumbnail_size Size of the thumbnail image. Defaults to
 *                                'album-archive'.
 * @param array   $attr Attributes to pass to `wp_get_attachment_image_src` -
 *                      this will probably be css classes.
 * @return boolean
 */
function album_archive_image_url( $post_id = null, $thumbnail_size = 'album-archive', $attr = array() ) {

	// Ensure the post id is set.
	if ( ! $post_id ) {

		$post_id = get_the_ID();

	}

	// Grab the featured image for the specified post.
	$image = wp_get_attachment_image_src( get_post_thumbnail_id( $post_id ), $thumbnail_size, false, $attr );

	// If there's no featured image then grab an attachment image and use that instead.
	if ( ! $image[0] ) {

		$images = get_attached_media( 'image', $post_id );

		if ( $images ) {
			foreach ( $images as $child_id => $attachment ) {

				$image = wp_get_attachment_image_src( $child_id, $thumbnail_size, false, $attr );
				break;

			}
		}
	}

	if ( is_array( $image ) ) {

		$image = $image[0];

	}

	if ( $image ) {

		return $image;

	} else {

		return false;

	}

}


/**
 * Fill empty post thumbnails with images from the first attachment added to a
 * post.
 *
 * @param string  $html Current html for thumbnail image.
 * @param integer $post_id ID for specified post.
 * @param integer $thumbnail_id ID for thumbnail image.
 * @param string  $size expected Thumbnail size.
 * @param array   $attr Image attributes.
 * @return string
 */
function album_post_thumbnail_html( $html, $post_id, $thumbnail_id, $size = '', $attr = array() ) {

	if ( empty( $html ) ) {

		$images = get_attached_media( 'image', $post_id );

		if ( $images ) {
			foreach ( $images as $child_id => $attachment ) {

				$html = wp_get_attachment_image( $child_id, $size, false, $attr );
				break;

			}
		}
	}

	return $html;

}

add_filter( 'post_thumbnail_html', 'album_post_thumbnail_html', 10, 5 );


/**
 * Prints HTML with meta information for the current post-date or time.
 *
 * The time is generated by {@see album_human_time_diff}.
 */
function album_post_time() {

	$time_string = sprintf(
		'<time class="entry-date published updated" datetime="%1$s">%2$s</time>',
		esc_attr( get_the_date( 'c' ) ),
		album_human_time_diff()
	);

	$posted_on = '<a href="' . esc_url( get_permalink() ) . '" rel="bookmark">' . $time_string . '</a>';

	echo '<span class="posted-on meta">' . $posted_on . '</span>'; /* WPCS: xss ok. */

}


/**
 * Prints HTML with the author meta data.
 */
function album_post_author() {

	if ( ! is_single() || is_attachment() ) {
		return;
	}

	$byline = sprintf(
		esc_html_x( 'by %s', 'post author', 'album' ),
		'<span class="author vcard"><a class="url fn n" href="' . esc_url( get_author_posts_url( get_the_author_meta( 'ID' ) ) ) . '">' . esc_html( get_the_author() ) . '</a></span>'
	);

	echo '<span class="byline meta"> ' . $byline . '</span>'; /* WPCS: xss ok. */

}


/**
 * Display a link to the Album Comments.
 *
 * Used in post meta, and adds a smooth scroll effect to add context to the
 * comments position.
 */
function album_comments_link() {

	if ( ! post_password_required() && get_comments_number() && post_type_supports( get_post_type(), 'comments' ) ) {

		$class = '';

		if ( is_singular() ) {
			$class = 'scroll-to';
		}

		echo '<span class="comment-count meta">';

		/* translators: %s: post title */
		comments_popup_link(
			sprintf(
				wp_kses(
					__( 'Leave a Comment<span class="screen-reader-text"> on %s</span>', 'album' ),
					array(
						'span' => array( 'class' => array() ),
					)
				),
				get_the_title()
			),
			false,
			false,
			$class
		);

		echo '</span>';

	}

}


/**
 * Get the posts custom read more text and, if available, display it instead of
 * 'read more'.
 */
function album_read_more_text() {

	// Get post data.
	$post = get_post();
	$custom_readmore = get_extended( $post->post_content );

	if ( ! empty( $custom_readmore['more_text'] ) ) {

		echo esc_html( $custom_readmore['more_text'] );
		return;

	}

	// Default text value.
	printf(
		esc_html__( 'Read more %s', 'album' ),
		the_title( '<span class="screen-reader-text">', '</span>', false )
	);

}


/**
 * Get a list of children pages for the current page.
 *
 * @return WP_Query
 */
function album_child_pages() {

	return new WP_Query(
		array(
			'post_type' => 'page',
			'orderby' => 'menu_order',
			'order' => 'ASC',
			'post_parent' => get_the_ID(),
			'posts_per_page' => 99,
			'no_found_rows' => true,
		)
	);

}


/**
 * Display a specific user and their contributor info.
 *
 * This is used at the end of blog posts, and on the contributor-page.php custom
 * page template.
 *
 * @param integer $user_id ID of current contributor.
 * @param integer $post_count Optional post could for current contributor. If
 *                            set then also display a list of recent blog posts.
 */
function album_contributor( $user_id = null, $post_count = null ) {

	// If no user id set then get the user for the current post.
	if ( ! $user_id ) {
		$user_id = get_the_author_meta( 'ID' );
	}

?>
	<div class="contributor entry-author">
		<?php echo get_avatar( $user_id, 140 ); ?>
		<h2>
			<a href="<?php echo esc_url( get_author_posts_url( $user_id ) ); ?>" class="author vcard">
				<?php the_author_meta( 'display_name', $user_id ); ?>
			</a>
		</h2>

<?php
	echo wpautop( esc_html( get_the_author_meta( 'description', $user_id ) ) ); // WPCS: XSS OK.
?>

		<p class="buttons">
			<a href="<?php echo esc_url( get_author_posts_url( $user_id ) ); ?>"><?php esc_html_e( 'All Posts &rarr;', 'album' ); ?></a>

			<?php echo album_author_website(); ?>
		</p>

	</div>
<?php

}


/**
 * Display the first category for the current blog post/ project.
 *
 * If any other post type is used then exit.
 */
function album_the_main_category() {

	$term_type = 'category';
	if ( 'jetpack-portfolio' === get_post_type() ) {
		$term_type = 'jetpack-portfolio-type';
	}

	$category = get_the_terms( get_the_ID(), $term_type );

	if ( is_array( $category ) ) {
		$category = current( array_values( $category ) );

		if ( is_object( $category ) ) {
?>
	<span class="post-lead-category meta"><a href="<?php echo esc_url( get_category_link( $category, $term_type ) ); ?>"><?php echo esc_html( $category->name ); ?></a></span>
<?php
		}
	}

}


/**
 * Display a list of all of the project categories.
 */
function album_project_terms() {

	$terms = get_terms(
		'jetpack-portfolio-type',
		array(
			'number' => 20,
			'orderby' => 'count',
			'order' => 'DESC',
		)
	);

	// Highlight currently selected page.
	$class = 'current-page';

	// Get the term for the current page.
	$current_term = get_term_by( 'slug', get_query_var( 'term' ), get_query_var( 'taxonomy' ) );

	// We're on a project category page, and not the main portfolio page, so reset the class.
	if ( $current_term ) {
		$class = '';
	}

	// Make sure the term exists and has some results.
	if ( is_wp_error( $terms ) || empty( $terms ) ) {
		return false;
	}

	// All clear - let's display the terms.
?>
	<div class="projects-terms">

		<strong class="project-terms-intro">
			<?php esc_html_e( 'Categories', 'album' ); ?>
		</strong>

		<a class="<?php echo esc_attr( $class ); ?>" href="<?php echo esc_url( home_url( '/portfolio/' ) ); ?>" data-tag="album-show-all"><?php esc_html_e( 'All', 'album' ); ?></a>

<?php
		foreach ( $terms as $t ) {
			$class = '';

			if ( $current_term && $current_term->term_id === (int) $t->term_id ) {
				$class = 'current-page';
			}

?>
		<a class="<?php echo esc_attr( $class ); ?>" href="<?php echo esc_url( get_term_link( $t ) ); ?>" data-tag="<?php echo esc_attr( $t->slug ); ?>"><?php echo esc_html( $t->name ); ?></a>
<?php
		}
?>
	</div>
<?php

}


/**
 * Display an SVG in the theme.
 *
 * @param string  $name Icon name.
 * @param boolean $echo Should the svg be printed or returned. If true the SVG
 *                      will be output directly. If false an svg use tag will be
 *                      returned.
 * @return string
 */
function album_svg( $name, $echo = true ) {

	$path = get_template_directory() . '/assets/svg/' . $name . '.svg';

	if ( $echo ) {

		// Return early if file does not exist.
		if ( ! file_exists( $path ) ) {
			return false;
		}

		// Output existing svg file.
		include( $path );

	} else {

		// Generate svg 'use' tag to display the svg.
		// Ensure svg can be found in assets/svg/svg.svg or it will not display.
		$svg = '<svg class="icon icon-' . esc_attr( $name ) . '" aria-hidden="true" role="img">';
		$svg .= '<use xlink:href="#' . esc_attr( $name ) . '"></use>';
		$svg .= '</svg>';

		return $svg;

	}

}


/**
 * Get a html link that points to the current authors website.
 *
 * @return string|false false if no author url found, otherwise a html link that points to the authors specified website.
 */
function album_author_website() {

	if ( get_the_author_meta( 'url' ) ) {
		return '<a href="' . esc_url( get_the_author_meta( 'url' ) ) . '" rel="author external">' . esc_html__( 'Website &rarr;', 'album' ) . '</a>';
	}

	return false;

}
